[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  # Environment variables should be set in Netlify dashboard under Site settings > Environment variables
  # VITE_SUPABASE_URL = "your_supabase_project_url"
  # VITE_SUPABASE_ANON_KEY = "your_supabase_anon_key"
  # VITE_OPENWEATHERMAP_API_KEY = "your_openweathermap_api_key"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
  Content-Security-Policy = "default-src 'self'; connect-src 'self' https://*.supabase.co wss://*.supabase.co https://*.tile.openstreetmap.org https://tile.openstreetmap.org https://api.openweathermap.org https://api.open-meteo.com https://api.openaq.org; img-src 'self' data: https://*; script-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' data: https://fonts.gstatic.com; frame-ancestors 'none';"
  Referrer-Policy = "strict-origin-when-cross-origin"
  X-Content-Type-Options = "nosniff"
  X-Frame-Options = "DENY"
  Permissions-Policy = "geolocation=(self), microphone=()"
  Cross-Origin-Opener-Policy = "same-origin"
  Cross-Origin-Embedder-Policy = "unsafe-none"
  Cross-Origin-Resource-Policy = "same-site"

# Long-term caching for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/js/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

# No caching for HTML
[[headers]]
  for = "/index.html"
  [headers.values]
  Cache-Control = "no-store"

