[build]
  publish = "dist"
  command = "npm ci --legacy-peer-deps && npm run build"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  # Environment variables should be set in Netlify dashboard under Site settings > Environment variables
  # VITE_SUPABASE_URL = "your_supabase_project_url"
  # VITE_SUPABASE_ANON_KEY = "your_supabase_anon_key"
  # VITE_OPENWEATHERMAP_API_KEY = "your_openweathermap_api_key"

# Asset routing - prevent assets from being redirected to index.html
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

[[redirects]]
  from = "/js/*"
  to = "/js/:splat"
  status = 200

# API routes (if any) - add specific patterns for API calls
# [[redirects]]
#   from = "/api/*"
#   to = "/.netlify/functions/:splat"
#   status = 200

# SPA fallback - only for app routes (must be last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# MIME type headers for assets
[[headers]]
  for = "*.css"
  [headers.values]
  Content-Type = "text/css; charset=utf-8"
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
  Content-Type = "application/javascript; charset=utf-8"
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.json"
  [headers.values]
  Content-Type = "application/json; charset=utf-8"

[[headers]]
  for = "*.woff2"
  [headers.values]
  Content-Type = "font/woff2"
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff"
  [headers.values]
  Content-Type = "font/woff"
  Cache-Control = "public, max-age=31536000, immutable"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
  # CSP: Added AQICN API and improved stylesheet handling
  Content-Security-Policy = "default-src 'self'; connect-src 'self' https://*.supabase.co wss://*.supabase.co https://*.tile.openstreetmap.org https://tile.openstreetmap.org https://api.openweathermap.org https://api.open-meteo.com https://api.openaq.org https://api.waqi.info https://ipapi.co; img-src 'self' data: https://*; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' data: https://fonts.gstatic.com; media-src 'self'; object-src 'none'; frame-ancestors 'none';"
  Referrer-Policy = "strict-origin-when-cross-origin"
  X-Content-Type-Options = "nosniff"
  X-Frame-Options = "DENY"
  Permissions-Policy = "geolocation=(self), microphone=()"
  Cross-Origin-Opener-Policy = "same-origin"
  Cross-Origin-Embedder-Policy = "unsafe-none"
  Cross-Origin-Resource-Policy = "same-site"

# Long-term caching for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/js/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

# No caching for HTML
[[headers]]
  for = "/index.html"
  [headers.values]
  Cache-Control = "no-store"

