[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  # Environment variables should be set in Netlify dashboard under Site settings > Environment variables
  # VITE_SUPABASE_URL = "your_supabase_project_url"
  # VITE_SUPABASE_ANON_KEY = "your_supabase_anon_key"
  # VITE_OPENWEATHERMAP_API_KEY = "your_openweathermap_api_key"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

