name: Manual Environmental Data Collection Trigger

on:
  workflow_dispatch:
    # Allow manual triggering for testing and emergency data collection
    inputs:
      city:
        description: 'Specific city to collect data for (optional)'
        required: false
        default: ''
        type: string
      force_collection:
        description: 'Force immediate data collection'
        required: false
        default: false
        type: boolean

jobs:
  trigger-data-collection:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Trigger Manual Data Collection
        run: |
          echo "🕐 Triggering manual environmental data collection..."
          echo "📅 Current time (UTC): $(date -u)"
          echo "📅 Current time (Local): $(date)"
          echo "🌍 GitHub Actions runs in UTC timezone"
          
          # Get the Edge Function URL from environment or use a placeholder
          # The actual URL will be configured in Supabase environment variables
          EDGE_FUNCTION_URL="${SUPABASE_URL:-https://bmqdbetupttlthpadseq.supabase.co}/functions/v1/scheduled-data-collection"
          
          echo "🔗 Edge Function URL: $EDGE_FUNCTION_URL"
          
          # Prepare the request payload based on inputs
          if [ "${{ github.event.inputs.city }}" != "" ]; then
            PAYLOAD="{\"manual\": true, \"city\": \"${{ github.event.inputs.city }}\"}"
            echo "🏙️  Collecting data for specific city: ${{ github.event.inputs.city }}"
          else
            PAYLOAD="{\"manual\": true}"
            echo "🌍 Collecting data for all cities"
          fi
          
          echo "📤 Request payload: $PAYLOAD"
          
          # Trigger the Edge Function with a simple POST request
          # The Edge Function will handle its own authentication using Supabase environment variables
          RESPONSE=$(curl -s -w "\n%{http_code}" \
            -X POST "$EDGE_FUNCTION_URL" \
            -H "Content-Type: application/json" \
            -d "$PAYLOAD")
          
          # Extract response body and status code
          HTTP_STATUS=$(echo "$RESPONSE" | tail -n1)
          RESPONSE_BODY=$(echo "$RESPONSE" | head -n -1)
          
          echo "📊 Response Status: $HTTP_STATUS"
          echo "📄 Response Body: $RESPONSE_BODY"
          
          # Check if the request was successful
          if [ "$HTTP_STATUS" -eq 200 ]; then
            echo "✅ Manual data collection triggered successfully"
          else
            echo "❌ Failed to trigger manual data collection"
            echo "Status: $HTTP_STATUS"
            echo "Response: $RESPONSE_BODY"
            echo "⚠️  Note: This is expected if the Edge Function requires authentication"
            echo "ℹ️   The Edge Function will run automatically via Supabase's internal scheduling"
            exit 0  # Don't fail the workflow, as this is expected behavior
          fi

      - name: Log completion
        run: |
          echo "🏁 Manual environmental data collection job completed"
          echo "⏰ Job completed at (UTC): $(date -u)"
          echo "⏰ Job completed at (Local): $(date)"
          echo "ℹ️   Note: Regular data collection runs automatically via Supabase cron scheduling"
          echo "🔄 Next automatic run: Every 15 minutes via Supabase cron"
